import math
import turtle

def draw_letter(turtle, letter, size=20):
    if letter == 'A':
        turtle.left(60)
        turtle.forward(size)
        turtle.right(120)
        turtle.forward(size)
        turtle.backward(size / 2)
        turtle.right(120)
        turtle.forward(size / 2)
        turtle.penup()
        turtle.backward(size / 2)
        turtle.left(120)
        turtle.forward(size/2)
        turtle.left(60)
        turtle.pendown()
    elif letter == 'B':
        turtle.left(90)
        turtle.forward(size)
        turtle.right(90)
        turtle.circle(-size / 4, 180)
        turtle.right(180)
        turtle.circle(-size / 4, 180)
        turtle.right(180)
    elif letter == 'C':
        turtle.circle(size / 2, -180)
        turtle.penup()
        turtle.backward(size)
        turtle.pendown()
    elif letter == 'D':
        turtle.forward(size)
        turtle.right(90)
        turtle.circle(-size / 2, 180)
        turtle.penup()
        turtle.backward(size)
        turtle.pendown()
    elif letter == 'E':
        turtle.forward(size)
        turtle.backward(size)
        turtle.right(90)
        turtle.forward(size / 2)
        turtle.left(90)
        turtle.forward(size)
        turtle.backward(size)
        turtle.right(90)
        turtle.forward(size / 2)
        turtle.left(90)
        turtle.penup()
        turtle.backward(size)
        turtle.pendown()
    elif letter == 'F':
        turtle.forward(size)
        turtle.backward(size)
        turtle.right(90)
        turtle.forward(size / 2)
        turtle.left(90)
        turtle.forward(size)
        turtle.backward(size)
        turtle.right(90)
        turtle.forward(size / 2)
        turtle.left(90)
        turtle.penup()
        turtle.backward(size)
        turtle.pendown()
    elif letter == 'G':
        turtle.circle(size / 2, 180)
        turtle.right(90)
        turtle.forward(size / 2)
        turtle.left(90)
        turtle.forward(size / 2)
        turtle.penup()
        turtle.backward(size)
        turtle.pendown()
    elif letter == 'H':
        turtle.left(90)
        turtle.forward(size)
        turtle.backward(size / 2)
        turtle.right(90)
        turtle.forward(size / 2)
        turtle.left(90)
        turtle.forward(size / 2)
        turtle.backward(size)
        turtle.penup()
        turtle.right(90)
    elif letter == 'I':
        turtle.left(90)
        turtle.forward(size)
        turtle.backward(size / 2)
        turtle.right(90)
        turtle.backward(size)
        turtle.penup()
        turtle.left(90)
        turtle.backward(size / 2)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'J':
        turtle.left(90)
        turtle.circle(-size / 4, -180)
        turtle.forward(size)
        turtle.backward(size)
        turtle.right(90)
        turtle.penup()
        turtle.forward(size / 2)
        turtle.pendown()
    elif letter == 'K':
        turtle.left(90)
        turtle.forward(size)
        turtle.backward(size / 2)
        turtle.right(45)
        turtle.forward(size / (2 * (2 ** 0.5)))
        turtle.backward(size / (2 * (2 ** 0.5)))
        turtle.right(90)
        turtle.forward(size / (2 * (2 ** 0.5)))
        turtle.penup()
        turtle.backward(size)
        turtle.pendown()
    elif letter == 'L':
        turtle.forward(size)
        turtle.backward(size)
        turtle.right(90)
        turtle.forward(size / 2)
        turtle.penup()
        turtle.backward(size / 2)
        turtle.left(90)
        turtle.pendown()
    elif letter == 'M':
        turtle.left(90)
        turtle.forward(size)
        turtle.right(135)
        turtle.forward(size / (2 * (2 ** 0.5)))
        turtle.left(90)
        turtle.forward(size / (2 * (2 ** 0.5)))
        turtle.right(135)
        turtle.forward(size)
        turtle.penup()
        turtle.left(90)
        turtle.backward(size / 2)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'N':
        turtle.left(90)
        turtle.forward(size)
        theta = 30
        theta_radian = math.pi / 180 * theta 
        turtle.right(180 - theta)
        turtle.forward(size / math.cos(theta_radian))
        turtle.left(180 - theta)
        turtle.forward(size)
        turtle.penup()
        turtle.backward(size)
        turtle.right(90)
    elif letter == 'O':
        turtle.circle(size / 2)
        turtle.penup()
        turtle.backward(size)
        turtle.pendown()
    elif letter == 'P':
        turtle.forward(size)
        turtle.right(90)
        turtle.circle(-size / 4, 180)
        turtle.penup()
        turtle.left(90)
        turtle.backward(size)
        turtle.pendown()
    elif letter == 'Q':
        turtle.circle(size / 2)
        turtle.penup()
        turtle.backward(size / 2)
        turtle.pendown()
        turtle.left(45)
        turtle.forward(size / (2 * (2 ** 0.5)))
        turtle.penup()
        turtle.backward(size / (2 * (2 ** 0.5)))
        turtle.pendown()
    elif letter == 'R':
        turtle.forward(size)
        turtle.right(90)
        turtle.circle(-size / 4, 180)
        turtle.right(180)
        turtle.circle(-size / 4, 90)
        turtle.penup()
        turtle.backward(size)
        turtle.pendown()
    elif letter == 'S':
        turtle.circle(size / 4, 180)
        turtle.right(90)
        turtle.penup()
        turtle.forward(size/2)
        turtle.pendown()
        turtle.left(90)
        turtle.circle(size/4, 180)
        turtle.penup()
        turtle.right(90)
        turtle.forward(size/2)
        turtle.left(90)
        turtle.forward(size/4)
    elif letter == 'T':
        turtle.left(90)
        turtle.forward(size)
        turtle.backward(size / 2)
        turtle.right(90)
        turtle.backward(size)
        turtle.penup()
        turtle.left(90)
        turtle.backward(size / 2)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'U':
        turtle.left(90)
        turtle.circle(-size / 2, 180)
        turtle.backward(size)
        turtle.penup()
        turtle.left(90)
        turtle.backward(size / 2)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'V':
        turtle.left(90)
        turtle.forward(size / 2)
        turtle.right(90)
        turtle.forward(size)
        turtle.backward(size)
        turtle.penup()
        turtle.left(90)
        turtle.backward(size / 2)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'W':
        turtle.left(90)
        turtle.forward(size)
        turtle.right(135)
        turtle.forward(size / (2 * (2 ** 0.5)))
        turtle.left(90)
        turtle.forward(size / (2 * (2 ** 0.5)))
        turtle.right(135)
        turtle.forward(size)
        turtle.penup()
        turtle.left(90)
        turtle.backward(size / 2)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'X':
        turtle.left(45)
        turtle.forward(size / (2 * (2 ** 0.5)))
        turtle.backward(size / (2 * (2 ** 0.5)))
        turtle.right(90)
        turtle.forward(size / (2 * (2 ** 0.5)))
        turtle.penup()
        turtle.backward(size / (2 * (2 ** 0.5)))
        turtle.left(45)
        turtle.pendown()
    elif letter == 'Y':
        turtle.left(90)
        turtle.forward(size / 2)
        turtle.right(30)
        turtle.forward(size / 2)
        turtle.backward(size / 2)
        turtle.left(60)
        turtle.forward(size / 2)
        turtle.backward(size / 2)
        turtle.right(30)
        turtle.backward(size/2)
        turtle.penup()
        turtle.right(90)
    elif letter == 'Z':
        turtle.forward(size)
        turtle.right(135)
        turtle.forward(size / (2 * (2 ** 0.5)))
        turtle.left(135)
        turtle.forward(size)
        turtle.penup()
        turtle.backward(size)
        turtle.pendown()
    # Add more letters as needed

# Create a turtle object
my_turtle = turtle.Turtle()

my_turtle.width(3)
# Turn off animation
# turtle.tracer(0)

# Set the speed of the turtle (0 is the fastest, 1 is slow, 10 is normal)
my_turtle.speed(2)

# Set the starting position
my_turtle.penup()
my_turtle.goto(-200, 0)
my_turtle.pendown()

# Write the word "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
word = "SHAYAN"
for letter in word:
    draw_letter(my_turtle, letter, size=100)
    my_turtle.penup()
    my_turtle.forward(40)  # Add spacing between letters
    my_turtle.pendown()

# Hide the turtle
my_turtle.hideturtle()

# Update the screen to show the final result
turtle.update()

# Display the window
turtle.done()
